/**
 * J Planet 1.4.2 - http://ateoriadadesevolucao.blogspot.com/p/software-j-planet.html
 */

/*
 * CadastroItensVendaJPanel.java
 *
 * Criado em 05/01/2020, 14:42:20
 */
package hdloja1.pkg1.janelas;

import hdloja1.pkg1.ItensVenda;
import hdloja1.pkg1.dao.GenericDAO;
import hdloja1.pkg1.dao.ItensVendaDAOImp;
import hdloja1.pkg1.util.EmptyFiledException;
import hdloja1.pkg1.util.RegraDeNegocio;
import java.awt.Color;
import javax.swing.JOptionPane;

public class CadastroItensVendaJPanel extends javax.swing.JPanel {

    private ItensVenda itensVenda;
    private GenericDAO dAO;
    private boolean editando = false;
    private NovoPrograma1Teste novoPrograma1Teste;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JButton jButtonVisualizarTudo;
    private javax.swing.JLabel jLabelIditensVenda;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JLabel jLabelVenda;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelQuantidade;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTituloCadastroItensVenda;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JFormattedTextField jFormattedTextFieldIditensVenda;
    private javax.swing.JFormattedTextField jFormattedTextFieldProduto;
    private javax.swing.JFormattedTextField jFormattedTextFieldVenda;
    private javax.swing.JFormattedTextField jFormattedTextFieldPreco;
    private javax.swing.JFormattedTextField jFormattedTextFieldQuantidade;
    private javax.swing.JFormattedTextField jFormattedTextFieldTotal;
    // End of variables declaration//GEN-END:variables

    /** Creates new form CadastroItensVendaJPanel */
    public CadastroItensVendaJPanel() {
        initComponents();
    } // fim do construtor CadastroItensVendaJPanel

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelTitulo = new javax.swing.JPanel();
        jLabelTituloCadastroItensVenda = new javax.swing.JLabel();
        jButtonUltimo = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonPrimeiro = new javax.swing.JButton();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVisualizarTudo = new javax.swing.JButton();
        jLabelIditensVenda = new javax.swing.JLabel();
        jFormattedTextFieldIditensVenda = new javax.swing.JFormattedTextField();
        jLabelProduto = new javax.swing.JLabel();
        jFormattedTextFieldProduto = new javax.swing.JFormattedTextField();
        jLabelVenda = new javax.swing.JLabel();
        jFormattedTextFieldVenda = new javax.swing.JFormattedTextField();
        jLabelPreco = new javax.swing.JLabel();
        jFormattedTextFieldPreco = new javax.swing.JFormattedTextField();
        jLabelQuantidade = new javax.swing.JLabel();
        jFormattedTextFieldQuantidade = new javax.swing.JFormattedTextField();
        jLabelTotal = new javax.swing.JLabel();
        jFormattedTextFieldTotal = new javax.swing.JFormattedTextField();

        jPanelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTituloCadastroItensVenda.setText("Cadastro ItensVenda");

        jPanelBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelBotoes.setLayout(new java.awt.GridBagLayout());

        jButtonVisualizarTudo.setText("Visualizar Tudo");
        jButtonVisualizarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarTudoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 11);
        jPanelBotoes.add(jButtonVisualizarTudo, gridBagConstraints);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hdloja1/pkg1/img/excluir.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        jPanelBotoes.add(jButtonExcluir, gridBagConstraints);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hdloja1/pkg1/img/editar.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        jPanelBotoes.add(jButtonEditar, gridBagConstraints);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hdloja1/pkg1/img/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        jPanelBotoes.add(jButtonSalvar, gridBagConstraints);

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hdloja1/pkg1/img/novo.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 6, 0);
        jPanelBotoes.add(jButtonNovo, gridBagConstraints);

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hdloja1/pkg1/img/seta_direita_dupla.png"))); // NOI18N
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hdloja1/pkg1/img/seta_direita.png"))); // NOI18N
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hdloja1/pkg1/img/seta_esquerda.png"))); // NOI18N
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        jButtonPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hdloja1/pkg1/img/seta_esquerda_dupla.png"))); // NOI18N
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelTituloLayout.createSequentialGroup()
                        .addComponent(jLabelTituloCadastroItensVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(jButtonPrimeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonProximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUltimo)))
                .addContainerGap())
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloCadastroItensVenda)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonPrimeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelIditensVenda.setText("Iditens Venda:");

        jFormattedTextFieldIditensVenda.setColumns(11);
        jFormattedTextFieldIditensVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldIditensVenda.setText("1");

        jLabelProduto.setText("Produto:");

        jFormattedTextFieldProduto.setColumns(11);
        jFormattedTextFieldProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabelVenda.setText("Venda:");

        jFormattedTextFieldVenda.setColumns(11);
        jFormattedTextFieldVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabelPreco.setText("Preco:");

        jFormattedTextFieldPreco.setColumns(10);
        jFormattedTextFieldPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.###############"))));

        jLabelQuantidade.setText("Quantidade:");

        jFormattedTextFieldQuantidade.setColumns(10);
        jFormattedTextFieldQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.###############"))));

        jLabelTotal.setText("Total:");

        jFormattedTextFieldTotal.setColumns(10);
        jFormattedTextFieldTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.###############"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIditensVenda)
                    .addComponent(jLabelProduto)
                    .addComponent(jLabelVenda)
                    .addComponent(jLabelPreco)
                    .addComponent(jLabelQuantidade)
                    .addComponent(jLabelTotal))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldIditensVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextFieldIditensVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelIditensVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProduto)
                            .addComponent(jFormattedTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVenda)
                            .addComponent(jFormattedTextFieldVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPreco)
                            .addComponent(jFormattedTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuantidade)
                            .addComponent(jFormattedTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotal)
                            .addComponent(jFormattedTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        restauraCampos(4);
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        itensVenda = (ItensVenda) dAO.consultaSeta(
                jFormattedTextFieldIditensVenda.getText(), 2); // consulta registro anterior

        if (itensVenda == null) {
            jButtonPrimeiro.setEnabled(false);
            jButtonAnterior.setEnabled(false);
        } // fim do if
        else {
            setDados(itensVenda);

            habilitaCampos(false, false);

            habilitaBotoes(false);

            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
        } // fim do else

        jButtonUltimo.setEnabled(true);
        jButtonProximo.setEnabled(true);
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        itensVenda = (ItensVenda) dAO.consultaSeta(
                jFormattedTextFieldIditensVenda.getText(), 3); // consulta proximo registro

        if (itensVenda == null) {
            jButtonUltimo.setEnabled(false);
            jButtonProximo.setEnabled(false);
        } // fim do if
        else {
            setDados(itensVenda);

            habilitaCampos(false, false);

            habilitaBotoes(false);

            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
        } // fim do else

        jButtonPrimeiro.setEnabled(true);
        jButtonAnterior.setEnabled(true);
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        restauraCampos(1);
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        novoPrograma1Teste.consultaItensVendaJPanel.limpaSelecao();
        limpaCampos();

        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);

        editando = false;
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        itensVenda = getDados();

        if (itensVenda != null) {
            if (editando) {
                dAO.altera(itensVenda);
            } else {
                dAO.adiciona(itensVenda);
            }

            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);

            restauraCampos(1);

            novoPrograma1Teste.consultaItensVendaJPanel.atualizaTabela(null);

            editando = false;
        } // fim do if
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        habilitaCampos(false, true);

        habilitaBotoes(true);

        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);

        editando = true;
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(
                jFormattedTextFieldIditensVenda.getText());

        int op = JOptionPane.showConfirmDialog(novoPrograma1Teste,
                "Tem certeza que deseja excluir IditensVenda " + id + "?");

        if (op == JOptionPane.YES_OPTION) {
            dAO.remove(id);

            restauraCampos(1);

            novoPrograma1Teste.consultaItensVendaJPanel.atualizaTabela(null);

            editando = false;
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonVisualizarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarTudoActionPerformed
        // TODO add your handling code here:
        novoPrograma1Teste.exibeJInternalFrameConsultaItensVenda();
    }//GEN-LAST:event_jButtonVisualizarTudoActionPerformed

    protected void setDados(ItensVenda itensVenda) {
        // labels dos campos de preenchimento obrigatorio
        jLabelIditensVenda.setForeground(Color.BLACK);
        jLabelProduto.setForeground(Color.RED);
        jLabelVenda.setForeground(Color.RED);
        jLabelPreco.setForeground(Color.RED);
        jLabelQuantidade.setForeground(Color.RED);
        jLabelTotal.setForeground(Color.RED);
        //
        jFormattedTextFieldIditensVenda.setText("" + itensVenda.getIditensVenda());
        jFormattedTextFieldProduto.setText("" + itensVenda.getProduto());
        jFormattedTextFieldVenda.setText("" + itensVenda.getVenda());
        jFormattedTextFieldPreco.setText(String.format("%.2f", itensVenda.getPreco()));
        jFormattedTextFieldQuantidade.setText(String.format("%.2f", itensVenda.getQuantidade()));
        jFormattedTextFieldTotal.setText(String.format("%.2f", itensVenda.getTotal()));
    } // fim do metodo setDados

    protected ItensVenda getDados() {
        itensVenda = null;

        // destaca labels dos campos de preenchimento obrigatorio
        jLabelIditensVenda.setForeground(Color.RED);
        jLabelProduto.setForeground(Color.RED);
        jLabelVenda.setForeground(Color.RED);
        jLabelPreco.setForeground(Color.RED);
        jLabelQuantidade.setForeground(Color.RED);
        jLabelTotal.setForeground(Color.RED);

        boolean continua = true;

        RegraDeNegocio regraDeNegocio = new RegraDeNegocio();

        try {
            regraDeNegocio.validaInteiro(jFormattedTextFieldIditensVenda.getText().trim());

            if (!editando && dAO.listaPorID(Integer.parseInt(
                    jFormattedTextFieldIditensVenda.getText())) != null) {
                System.out.println(jLabelIditensVenda.getText() + " possui valor duplicado!");

                JOptionPane.showMessageDialog(null,
                        jLabelIditensVenda.getText() + " possui valor duplicado!");

                continua = false;
            } else {
                jLabelIditensVenda.setForeground(Color.BLACK);
            }
        } catch (EmptyFiledException ex) {
            System.out.println(jLabelIditensVenda.getText() + " deve ser preenchido!");

            JOptionPane.showMessageDialog(null, jLabelIditensVenda.getText() + " deve ser preenchido!");
        } catch (NumberFormatException ex) {
            System.out.println(jLabelIditensVenda.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros inteiros.");

            JOptionPane.showMessageDialog(null, jLabelIditensVenda.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros inteiros.");

            continua = false;
        } // fim do catch

        try {
            regraDeNegocio.validaInteiro(jFormattedTextFieldProduto.getText().trim());

            jLabelProduto.setForeground(Color.BLACK);
        } catch (EmptyFiledException ex) {
            System.out.println(jLabelProduto.getText() + " deve ser preenchido!");

            JOptionPane.showMessageDialog(null, jLabelProduto.getText() + " deve ser preenchido!");
        } catch (NumberFormatException ex) {
            System.out.println(jLabelProduto.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros inteiros.");

            JOptionPane.showMessageDialog(null, jLabelProduto.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros inteiros.");

            continua = false;
        } // fim do catch

        try {
            regraDeNegocio.validaInteiro(jFormattedTextFieldVenda.getText().trim());

            jLabelVenda.setForeground(Color.BLACK);
        } catch (EmptyFiledException ex) {
            System.out.println(jLabelVenda.getText() + " deve ser preenchido!");

            JOptionPane.showMessageDialog(null, jLabelVenda.getText() + " deve ser preenchido!");
        } catch (NumberFormatException ex) {
            System.out.println(jLabelVenda.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros inteiros.");

            JOptionPane.showMessageDialog(null, jLabelVenda.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros inteiros.");

            continua = false;
        } // fim do catch

        try {
            regraDeNegocio.validaPontoFlutuante(jFormattedTextFieldPreco.getText().trim());

            jLabelPreco.setForeground(Color.BLACK);
        } catch (EmptyFiledException ex) {
            System.out.println(jLabelPreco.getText() + " deve ser preenchido!");

            JOptionPane.showMessageDialog(null, jLabelPreco.getText() + " deve ser preenchido!");
        } catch (NumberFormatException ex) {
            System.out.println(jLabelPreco.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros.");

            JOptionPane.showMessageDialog(null, jLabelPreco.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros.");

            continua = false;
        } // fim do catch

        try {
            regraDeNegocio.validaPontoFlutuante(jFormattedTextFieldQuantidade.getText().trim());

            jLabelQuantidade.setForeground(Color.BLACK);
        } catch (EmptyFiledException ex) {
            System.out.println(jLabelQuantidade.getText() + " deve ser preenchido!");

            JOptionPane.showMessageDialog(null, jLabelQuantidade.getText() + " deve ser preenchido!");
        } catch (NumberFormatException ex) {
            System.out.println(jLabelQuantidade.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros.");

            JOptionPane.showMessageDialog(null, jLabelQuantidade.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros.");

            continua = false;
        } // fim do catch

        try {
            regraDeNegocio.validaPontoFlutuante(jFormattedTextFieldTotal.getText().trim());

            jLabelTotal.setForeground(Color.BLACK);
        } catch (EmptyFiledException ex) {
            System.out.println(jLabelTotal.getText() + " deve ser preenchido!");

            JOptionPane.showMessageDialog(null, jLabelTotal.getText() + " deve ser preenchido!");
        } catch (NumberFormatException ex) {
            System.out.println(jLabelTotal.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros.");

            JOptionPane.showMessageDialog(null, jLabelTotal.getText() + " possui valor incorreto!\n"
                    + "Digite somente numeros.");

            continua = false;
        } // fim do catch

        if (continua) {
            itensVenda = new ItensVenda();

            itensVenda.setIditensVenda(Integer.parseInt(
                    jFormattedTextFieldIditensVenda.getText()));
            try {
                itensVenda.setProduto(Integer.parseInt(
                        jFormattedTextFieldProduto.getText()));
            } catch (NumberFormatException ex) {
                itensVenda.setProduto(0);
            }

            try {
                itensVenda.setVenda(Integer.parseInt(
                        jFormattedTextFieldVenda.getText()));
            } catch (NumberFormatException ex) {
                itensVenda.setVenda(0);
            }

            try {
                itensVenda.setPreco(Double.parseDouble(
                        jFormattedTextFieldPreco.getText().replace(",", ".")));
            } catch (NumberFormatException ex) {
                itensVenda.setPreco(0);
            }

            try {
                itensVenda.setQuantidade(Double.parseDouble(
                        jFormattedTextFieldQuantidade.getText().replace(",", ".")));
            } catch (NumberFormatException ex) {
                itensVenda.setQuantidade(0);
            }

            try {
                itensVenda.setTotal(Double.parseDouble(
                        jFormattedTextFieldTotal.getText().replace(",", ".")));
            } catch (NumberFormatException ex) {
                itensVenda.setTotal(0);
            }

        } // fim do if continua

        return itensVenda;
    } // fim do metodo getDados

    public final void restauraCampos(int seta) {
        itensVenda = (ItensVenda) dAO.consultaSeta("", seta);

        if (itensVenda != null) {
            setDados(itensVenda);

            habilitaBotoes(false);

            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);

            switch (seta) {
                case 1:
                    jButtonPrimeiro.setEnabled(false);
                    jButtonAnterior.setEnabled(false);
                    jButtonUltimo.setEnabled(true);
                    jButtonProximo.setEnabled(true);
                    break;
                case 4:
                    jButtonPrimeiro.setEnabled(true);
                    jButtonAnterior.setEnabled(true);
                    jButtonUltimo.setEnabled(false);
                    jButtonProximo.setEnabled(false);
                    break;
            } // fim do switch

            habilitaCampos(false, false);
        } // fim do if
        else {
            limpaCampos();

            jButtonPrimeiro.setEnabled(false);
            jButtonAnterior.setEnabled(false);
            jButtonUltimo.setEnabled(false);
            jButtonProximo.setEnabled(false);
        } // fim do else
    } // fim do metodo restauraCampos

    protected void limpaCampos() {
        jFormattedTextFieldIditensVenda.setText("" + dAO.consultaProximoID());
        jFormattedTextFieldProduto.setText("0");
        jFormattedTextFieldVenda.setText("0");
        jFormattedTextFieldPreco.setText("0,00");
        jFormattedTextFieldQuantidade.setText("0,00");
        jFormattedTextFieldTotal.setText("0,00");

        habilitaBotoes(true);

        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);

        habilitaCampos(true, true);
    } // fim do metodo limpaCampos

    protected void habilitaCampos(boolean habilitadoID, boolean habilitado) {
        jFormattedTextFieldIditensVenda.setEditable(habilitadoID);
        jFormattedTextFieldProduto.setEditable(habilitado);
        jFormattedTextFieldVenda.setEditable(habilitado);
        jFormattedTextFieldPreco.setEditable(habilitado);
        jFormattedTextFieldQuantidade.setEditable(habilitado);
        jFormattedTextFieldTotal.setEditable(habilitado);
    } // fim do metodo habilitaCampos

    private void habilitaBotoes(boolean habilitado) {
        jButtonSalvar.setEnabled(habilitado);
    } // fim do metodo habilitaBotoes

    protected void editaRegistro(int id) {
        itensVenda = (ItensVenda) dAO.listaPorID(id);
        setDados(itensVenda);

        habilitaCampos(false, true);

        habilitaBotoes(true);

        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);

        editando = true;
    } // fim do metodo editaRegistro

    protected void excluiRegistro(int id) {
        dAO.remove(id);

        editando = false;

        restauraCampos(1);
    } // fim do metodo excluiRegistro

    protected void setFrame(NovoPrograma1Teste frame) {
        novoPrograma1Teste = frame;

        dAO = new ItensVendaDAOImp(frame);

        restauraCampos(1);
    } // fim do metodo setFrame
} // fim da classe CadastroItensVendaJPanel
